FROM python:3.7-alpine

WORKDIR /src
COPY requirements.txt /src/
RUN apk add --update gcc libc-dev linux-headers python3-dev && pip install -r requirements.txt && rm -rf /var/cache/apk/*

COPY ./get-processes.py /src/

CMD [ "python", "-u", "/src/get-processes.py" ]