version: '3.7'

services:
  # pushgateway:
  #   image: mon-pushgateway:latest
  #   build:
  #       dockerfile: Dockerfile-pushgateway
  #       context: .
  #   ports:
  #     - 9091:9091
  #   restart: always
  #   networks:
  #     - monitor

  monitor:
    image: mon-get-processes:latest
    build:
        dockerfile: Dockerfile-monitor
        context: .
    privileged: true
    pid: host
    environment:
      - MON_PUSHGATEWAY_HOST=192.168.178.26
      - MON_PUSHGATEWAY_PORT=9091
    cap_add:
      - ALL
    restart: always
    networks:
      - monitor

networks:
  monitor:

