FROM alpine:latest

ENV VER=pushgateway-0.9.0.linux-386.tar.gz
ENV DIR=pushgateway-0.9.0.linux-386

RUN wget https://github.com/prometheus/pushgateway/releases/download/v0.9.0/$VER 
RUN tar xzf $VER 
RUN cp $DIR/pushgateway /usr/local/bin/ 

EXPOSE 9091

CMD [ "/usr/local/bin/pushgateway" ]