version: '3.7'

services:
  monitor:
    image: mon-get-processes:latest
    build:
        dockerfile: Dockerfile-monitor
        context: .
    privileged: true
    pid: host
    environment:
      - MON_PUSHGATEWAY_HOST=192.168.178.26
      - MON_PUSHGATEWAY_PORT=9091
      - MON_SECONDS_DELAY_BETWEEN_MONITOR_REQUESTS=2
    env_file: monitoring.env
    cap_add:
      - ALL
    restart: always
    networks:
      - monitor

networks:
  monitor:
